#!/bin/bash
#
# The 'run' performs a simple test that verifies that image
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

IMAGE_NAME=${IMAGE_NAME-ausnimbus/s2i-python:3.6}
VERSION=${VERSION-"3.6"}
S2I_ARGS=${S2I_ARGS:-""}

# mod_wsgi does not work on alpine
if [ $VARIANT == "alpine" ]; then
  # uwsgi does not work on alpine 2.7
  if [ $VERSION == "2.7" ]; then
    TEST_APPS=({standalone,setup,django,numpy,locale})
  else
    TEST_APPS=({standalone,setup,django,numpy,uwsgi,locale})
  fi
else
  TEST_APPS=({standalone,setup,django,numpy,uwsgi,locale,mod-wsgi})
fi

VERSION_COMMAND='env'

extra_tests() {
  echo ""
}

test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
source ${test_dir}/../common/tests/s2i
