#!/bin/bash
#
# The 'run' performs a simple test that verifies that STI image.
# The main focus here is to excersise the STI scripts.
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

IMAGE_NAME=${IMAGE_NAME-ausnimbus/s2i-python:3.6}
VERSION=${VERSION-"3.6"}
S2I_ARGS=${S2I_ARGS:-""}

#TEST_APPS=({mod-wsgi,standalone,setup,django,numpy,app-home,uwsgi,locale})
TEST_APPS=({standalone,setup,django,numpy,app-home,uwsgi,locale})
VERSION_COMMAND="python --version"
EXTRA_TESTS=""

test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
source ${test_dir}/../common/tests/functions
