#!/bin/bash -e

NAME="python"
DISPLAY_NAME="Python"
TYPE="s2i"
VARIANTS=${VARIANTS:-"default,alpine"}
VERSIONS=${VERSIONS:-"2.7,3.6"}

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
