#!/bin/bash

NAME="python"
DISPLAY_NAME="Python"
TYPE="s2i"
VARIANT="alpine"
VERSIONS="2.7,3.6"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
